apiVersion: v1
kind: Pod
metadata:
  name: kot
spec:
  containers:
  - name: test123
    imagePullPolicy: IfNotPresent
    image: controller:latest
    ports:
    - containerPort: 80
  serviceAccountName: custom-service-account

