---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-service-account
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: custom-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: custom-cluster-role
  apiGroup: rbac.authorization.k8s.io

