apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: nginx-1
    engironment: demo
    # hello: world
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
