apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: nginx-2
    engironment: demo
    hello: world
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
